### ISSUE TITLE
Daemon mode not works

### ISSUE THREAD

**Issue by Thanatermesis** [Obsidian-StudiosInc/entrance#41] opened 2020-02-02 20:37 UTC
Entrance can be run with --nodaemon, but if you don't include this option it doesn't seems to work well (theme issues, no WM-sessions found, etc)

**Comment by wltjr** [comment] 2020-02-02 21:06
It sounds like you ran into issue #34. That is more due to changes in EFL I have not had the chance to resolve. I have spent time looking into it, and I hope it is something I can fix. I think they changed how EFL handles file descriptors which might pose a greater issue to resolve for Entrance. Thus, that issue remaining open for sometime. I need to dig back into it again.

**Comment by wltjr** [comment] 2020-02-04 04:30
@Thanatermesis if you would, please try the same as above with autologin enabled. Then, after you log in via autologin, log out. If you see the missing UI bits, that will be confirmation you ran into issue #34. For whatever reason, when you start entrance the client fails to connect to server and does not get the sessions and other things to populate the UI. But, if you log in via autologin and then log out, the client does connect. There is some odd initialization that is causing issue #34 

If you log in via autologin, then log out, and you still do not get a complete UI. Then, you ran into a new issue I need to look into. Thank you very much!

**Comment by wltjr** [comment] 2020-03-20 22:26
@Thanatermesis any further information here? If not, I will close as a duplicate of #34. Thanks!

**Closed** 2020-03-21 00:03 UTC

**Comment by wltjr** [comment] 2020-03-21 00:07
Ok, thank you! I believe this is the same issue as #34. I will get onto that issue ASAP. It has been an issue for too long...

**Comment by Thanatermesis** [comment] 2020-03-21 00:09
Yeah from what I see it should be caused by the same reason
