### ISSUE TITLE
Entrance reading cairo-dock as an Xsession even though it's type Application

### ISSUE THREAD

**Issue by TheTechRobo** [Obsidian-StudiosInc/entrance#50] opened 2020-11-24 22:37 UTC
## Description
As stated by @Thanatermesis:  
The issue is from entrance reading the .desktop incorrectly, see:

    ~ ❯❯❯ grep "^Type=" /usr/share/xsessions/e16-session.desktop
    Type=XSession
    ~ ❯❯❯ grep "^Type=" /usr/share/xsessions/cairo-dock.desktop
    Type=Application

I don't know why cairo-dock is on this directory but in any case is not the correct type of .desktop file that should be used for init X sessions, so entrance should only consider the ones of type XSession

## Steps to reproduce
1. Install Cairo-Dock
2. Make sure that the .desktop file is in /usr/share/xsessions
3. Launch Entrance

## How entrance is started (doesn't matter)
I installed it with Apt, does this answer your question?  
I think systemd.

## System information
- OS/Distro: elive 3.8.17
- Pam enabled: Idk (doesn't matter)
- Consolekit enabled: NO
- Systemd or other init (openrc, sysvinit, etc): Systemd (doesn't matter)
- EFL Version: Git i think (doesn't matter)

**Comment by wltjr** [comment] 2020-12-04 22:28
Thanks for the report. I will see about adding code to ignore the unwanted types in desktop files. It is not likely to happen till after the 15th, but it is on my TODO list, and it should not require too much to fix. Thank you for the report, and sorry for the issues!

**Comment by TheTechRobo** [comment] 2020-12-05 02:45
> Sorry for the issues!

No problem! Thanks for making Entrance actually work OK!

**Comment by wltjr** [comment] 2020-12-19 17:38
@TheTechRobo after looking further into this issue, I do not think it can be resolved as intended. Starting with the [desktop specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-1.0.html#recognized-keys), it only lists three types, application, link, and directory. That rules out using a type of xsession, as that is not valid. While it could be a valid custom type, it is not standard, and not too many things use that. Entrance accesses those files via [efreet desktop support](https://github.com/Obsidian-StudiosInc/entrance/blob/master/src/daemon/entrance_session.c#L500), which per the spec, reads the [type field](https://github.com/Enlightenment/efl/blob/master/src/lib/efreet/efreet_desktop.h#L90) as a integer not a string. That makes reading custom types very difficult, if not unknown.

Then there are the things using `Type=Application`. Even [Enlightenment itself](https://github.com/Enlightenment/enlightenment/blob/master/data/session/enlightenment.desktop.in) lists its type as an application. Another example is the [xsession.desktop](https://github.com/gentoo/gentoo/blob/master/x11-apps/xinit/files/Xsession.desktop) file used with xinit, that also uses application. Given the amount of things using application, that is not a type that could be ignored without causing a lot of issues. Trying to get other things to switch to xsession from application would probably not be very successful. 

It seems the best solution would be to change the location of cairo-dock.desktop file. Otherwise, entrance would need some sort of blacklist to ignore certain desktop files found in the default location. But as for ignoring them based on type, that does not seem to be a viable option. Therefore, I will close this issue, as short of implementing a black list, which I may be open to, but would need more than just a single application to justify that effort, there does not seem to be any way to resolve this issue in entrance. Sorry, I took a look, and am sympathetic to the issue, but have to resolve it in other ways. Thanks!

**Closed by wltjr** 2020-12-19 17:38 UTC

**Comment by TheTechRobo** [comment] 2020-12-19 17:41
Sounds good. I'll let you know if there's any other conflicts with applications.
